name = "discord_luau/example"
private = true
version = "0.0.2"
description = "Discord-Luau Example - Example/Test scripts for discord-luau."
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
repository = "https://github.com/DiscordLuau/discord-luau/tree/main/packages/formdata"
pesde_version = "0.7.1"

includes = ["src/**/*", "pesde.toml", "LICENSE", "README.md", "CONTRIBUTING.md", "patches/**/*"]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "luau"
lib = "src/init.luau"

[dependencies]
discord = { name = "discord_luau/discord_luau", version = "0.0.2" }
builders = { name = "discord_luau/builders", version = "0.0.2" }
classes = { name = "discord_luau/classes", version = "0.0.3" }
opus = { name = "discord_luau/opus", version = "0.0.2" }

[patches]
"yetanotherclown/luau_futures" = { "2.0.0-beta.3 luau" = "patches/yetanotherclown+luau_futures-2.0.0-beta.3+luau.patch" }
