[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.31.0"
lune = "lune-org/lune@0.8.8"
# moonwave-extractor = "evaera/moonwave@1.1.3"
selene = "Kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
darklua = "seaofvoices/darklua@0.13.1"
pesde = "pesde-pkg/pesde@0.5.0-rc.13"