local DiscordLuau = require("Package")

export type ApplicationCommandBuilder = DiscordLuau.ApplicationCommandBuilder
export type ApplicationCommandOptionBuilder = DiscordLuau.ApplicationCommandOptionBuilder
export type DiscordActivityBuilder = DiscordLuau.DiscordActivityBuilder
export type DiscordAutomoderationRuleBuilder = DiscordLuau.DiscordAutomoderationRuleBuilder
export type DiscordEmbedBuilder = DiscordLuau.DiscordEmbedBuilder
export type DiscordIntentsBuilder = DiscordLuau.DiscordIntentsBuilder
export type DiscordModalBuilder = DiscordLuau.DiscordModalBuilder
export type DiscordPermissionsBuilder = DiscordLuau.DiscordPermissionsBuilder
export type DiscordPresenceBuilder = DiscordLuau.DiscordPresenceBuilder
export type DiscordSettingsBuilder = DiscordLuau.DiscordSettingsBuilder

export type DiscordClient = DiscordLuau.DiscordClient

export type DiscordApplication = DiscordLuau.DiscordApplication
export type DiscordAutomoderationRule = DiscordLuau.DiscordAutomoderationRule
export type DiscordCache = DiscordLuau.DiscordCache
export type DiscordChannel = DiscordLuau.DiscordChannel
export type DiscordEmoji = DiscordLuau.DiscordEmoji
export type DiscordGuild = DiscordLuau.DiscordGuild
export type DiscordGuildMember = DiscordLuau.DiscordGuildMember
export type DiscordGuildRole = DiscordLuau.DiscordGuildRole
export type DiscordInteraction = DiscordLuau.DiscordInteraction
export type DiscordInvite = DiscordLuau.DiscordInvite
export type DiscordMessage = DiscordLuau.DiscordMessage
export type DiscordTextChannel = DiscordLuau.DiscordTextChannel
export type DiscordVoiceChannel = DiscordLuau.DiscordVoiceChannel
export type DiscordUser = DiscordLuau.DiscordUser

return DiscordLuau