name = "discord_luau/commands"
version = "0.0.3"
description = "Discord-Luau Commands - A commands framework for discord-luau."
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
repository = "https://github.com/DiscordLuau/discord-luau/tree/main/packages/commands"
pesde_version = "0.7.0-rc.7"

includes = [
    "src/**/*",
    "pesde.toml",
    "LICENSE",
    "README.md",
    "CONTRIBUTING.md",
    "patches/**/*",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "luau"
lib = "src/init.luau"

[dependencies]
std_polyfills = { name = "discord_luau/std_polyfills", version = ">=0.0.0" }
builders = { name = "discord_luau/builders", version = ">=0.0.0" }
classes = { name = "discord_luau/classes", version = ">=0.0.0" }
api_types = { name = "discord_luau/api_types", version = ">=0.0.0" }
future = { name = "yetanotherclown/luau_futures", version = "2.0.0-beta.3" }
logger = { name = "discord_luau/logger", version = ">=0.0.0" }

[patches]
"yetanotherclown/luau_futures" = { "2.0.0-beta.3 luau" = "patches/yetanotherclown+luau_futures-2.0.0-beta.3+luau.patch" }
