---
blank_issues_enabled: false
contact_links:
  - name: Discord-Luau's Discord Server
    url: https://discord.com/invite/DpQwdD8zD3
    about: Please ask and answer questions here. (You can find us in the #projects channel!)
