name = "discord_luau/std_polyfills"
version = "0.0.1"
description = "Discord-Luau Polyfills - polyfills for stdlib functions."
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
repository = "https://github.com/DiscordLuau/discord-luau/tree/Master/packages/std_polyfills"
pesde_version = "0.5.2"

includes = ["src/**/*", "pesde.toml", "LICENSE", "CONTRIBUTING.md"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
