name = "discord_luau/classes"
version = "0.1.0"
description = "Discord-Luau Classes - Objects that wrap around various discord API structures."
license = "MIT"
authors = ["AsyncMatrix <catbob614@gmail.com>"]
repository = "https://github.com/DiscordLuau/discord-luau"
pesde_version = "0.5.0-rc.13"

includes = ["src/**", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
std_polyfills = { workspace = "discord_luau/std_polyfills" }
api_types = { workspace = "discord_luau/api_types" }
utilities = { workspace = "discord_luau/utilities" }
state = { workspace = "discord_luau/state" }
async = { workspace = "discord_luau/async" }
builders = { workspace = "discord_luau/builders" }
rest = { workspace = "discord_luau/rest" }
bit = { workspace = "discord_luau/bit", target = "luau" }