name = "discord_luau/buffer"
version = "0.1.0"
description = "Discord-Luau Buffer - Used to temporarily storing encoded data."
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"

includes = ["src/**", "pesde.toml"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"