return {
	GuildMembers = "GuildMembers",
	GuildModeration = "GuildModeration",
	GuildEmojisAndStickers = "GuildEmojisAndStickers",
	GuildIntegrations = "GuildIntegrations",
	GuildWebhooks = "GuildWebhooks",
	GuildInvites = "GuildInvites",
	GuildVoiceState = "GuildVoiceState",
	GuildPresences = "GuildPresences",
	GuildMessage = "GuildMessage",
	GuildMessageReactions = "GuildMessageReactions",
	GuildMessageTyping = "GuildMessageTyping",

	DirectMessage = "DirectMessage",
	DirectMessageReactions = "DirectMessageReactions",
	DirectMessageTyping = "DirectMessageTyping",

	GuildMessageContent = "GuildMessageContent",
	GuildScheduledEvents = "GuildScheduledEvents",
	GuildModerationConfiguration = "GuildModerationConfiguration",
	GuildModerationExecution = "GuildModerationExecution",
}