name = "discord_luau/core"
version = "0.1.0"
description = "Discord-Luau Core - The entrypoint for the Discord Luau library."
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"

includes = ["src/**", "pesde.toml"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
std_polyfills = { workspace = "discord_luau/std_polyfills" }
api_types = { workspace = "discord_luau/api_types" }
utilities = { workspace = "discord_luau/utilities" }
state = { workspace = "discord_luau/state" }
async = { workspace = "discord_luau/async" }
builders = { workspace = "discord_luau/builders" }
rest = { workspace = "discord_luau/rest" }
classes = { workspace = "discord_luau/classes" }
logger = { workspace = "discord_luau/logger" }
bit = { workspace = "discord_luau/bit", target = "luau" }
emitter = { workspace = "discord_luau/emitter", target = "luau" }