name = "discord_luau/discord_luau"
version = "0.0.1"
description = "Discord-Luau - The entrypoint for the Discord Luau library."
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
repository = "https://github.com/DiscordLuau/discord-luau/tree/main/packages/discord_luau"
pesde_version = "0.7.0-rc.7"

includes = ["src/**/*", "pesde.toml", "LICENSE", "README.md", "CONTRIBUTING.md", "patches/**/*"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
std_polyfills = { name = "discord_luau/std_polyfills", version = "0.0.2" }
api_types = { name = "discord_luau/api_types", version = "0.0.2" }
util = { name = "discord_luau/util", version = "0.0.1" }
state = { name = "discord_luau/state", version = "0.0.1" }
future = { name = "yetanotherclown/luau_futures", version = "2.0.0-beta.3" }
builders = { name = "discord_luau/builders", version = "0.0.2" }
rest = { name = "discord_luau/rest", version = "0.0.1" }
classes = { name = "discord_luau/classes", version = "0.0.3" }
logger = { name = "discord_luau/logger", version = "0.0.1" }
bit = { name = "discord_luau/bit", version = "0.0.2" }
emitter = { name = "discord_luau/emitter", version = "0.0.1" }

[patches]
"yetanotherclown/luau_futures" = { "2.0.0-beta.3 luau" = "patches/yetanotherclown+luau_futures-2.0.0-beta.3+luau.patch" }
