name = "discord_luau/voice"
version = "0.1.0"
description = "Discord Luau Voice - Implementation of the voice protocol for discord."
license = "MIT"
authors = ["AsyncMatrix<https://github.com/4x8Matrix>"]
repository = "https://github.com/DiscordLuau/discord-luau"

includes = ["src/**", "pesde.toml"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"