name: Moonwave Documentation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ok-nick/setup-aftman@v0.4.2
      - name: Generate Standard Library
        run: selene generate-roblox-std
      - name: Run Moonwave Extract
        run: moonwave extract packages/discord-luau
