name: Selene Linter

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ok-nick/setup-aftman@v0.4.2
      - name: Lint Packages
        run: lune run task lint
